name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install nuget dependencies
        run: nuget restore SuperBMD.sln
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: msbuild SuperBMD.sln /t:Build /property:Configuration=Release
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: SuperBMD
          path: SuperBMD\bin\Release\*
